SELECT CAR_ID, A.CAR_TYPE,
FLOOR(DAILY_FEE * 30 * (1-DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
AND B.DURATION_TYPE = '30일 이상'
HAVING FEE BETWEEN 500000 AND 2000000

ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC