SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO AS RES1
WHERE FAVORITES = (
    SELECT MAX(FAVORITES)
    FROM REST_INFO AS RES2
    WHERE RES1.FOOD_TYPE = RES2.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC