-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS AS A
JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE 'Intact%' 
AND (B.SEX_UPON_OUTCOME LIKE 'Neutered%' OR B.SEX_UPON_OUTCOME LIKE 'Spayed%')
ORDER BY A.ANIMAL_ID


# SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
# FROM ANIMAL_INS I 
# JOIN ANIMAL_OUTS O 
# USING(ANIMAL_ID)
# WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' 
#       AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%' 
#            OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')      
# ORDER BY I.ANIMAL_ID  