-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE AS A
JOIN REST_REVIEW AS B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE MEMBER_NAME = (
    SELECT MEMBER_NAME
    FROM MEMBER_PROFILE AS A
    JOIN REST_REVIEW AS B
    ON A.MEMBER_ID = B.MEMBER_ID
    GROUP BY MEMBER_NAME
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
